# 定义要生成的段落
IntroParagraph:
  keys: [PK_1.C_max, PK_1.T_max, PK_1.t_1_2]
  prompt: prompts/gen_intro.txt

MethodParagraph:
  keys: [PD.T_max]
  prompt: prompts/gen_method.txt

# StabilityParagraph:
#   keys: [age, weight]
#   prompt: prompts/gen_stability.txt
